server:
  port: 28080

spring:

  application:
    name: mybatis-example

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
