server:
  port: 28080

spring:

  application:
    name: mybatis-example

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    com.example.mybatis.mybatis.mapper.**: trace
